from pytube import YouTube
from pytube import Playlist
import webbrowser
from tkinter import *
import tkinter.messagebox
import base64
import os
from tkinter import filedialog



#**********************************



icon=''''
AAABAAEAMDAAAAEAIACoJQAAFgAAACgAAAAwAAAAYAAAAAEAIAAAAAAAgCUAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/78/BN+7XTHivmE/4r5hP+K+YT/ivmE/
4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/i
vmE/4r5hP+K+YT/ivmE/57lcFgAAAAAAAAAA/wAAAeK+YEfhvGCi4r5g3OK+YPjivmD44r5g3OG8
YKLivmBH//8AAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivmBH4b1h
4uK+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/
4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/hvWCz2rZIBwAAAADlv18o4r5hxeG9YP7i
vmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/hvWD+4r5hxd+6XSkAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAOC8YSrhvmD24r5hzeG9YFXivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5h
P+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/atkgH
AAAAAOO7X0DivmDx4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+YPHj
v19AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOK+YJbivmDw1rtdEwAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA5b9fKOK+YPHivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/
4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmDx37pdKQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOK+YLvi
vmHCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAB4r5hxeK+Yf/ivmH/4r5h
/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5hxf//AAEAAAAA
AAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AADivmBH4b1g/uK+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h
/+K+Yf/ivmH/4b1g/uK+YEcAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhvGCi4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+G9
YOHhvWDh4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+G8YKIAAAAAAAAAAAAAAAAAAAAAAAAA
AOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivmDc4r5h/+K+Yf/i
vmH/4r5h/+K+Yf/ivmH/4r5g1um/VQzpv1UM4r1g1uK+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+
YNwAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAADivmD44r5h/+K+Yf/ivmH/4r5h/+K+Yf/hvWD45LtdMQAAAAAAAAAA37tdMeK9Yffi
vmH/4r5h/+K+Yf/ivmH/4r5h/+K+YPgAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivmD44r5h/+K+Yf/ivmH/4r5h/+K+Yf/hvmBy
AAAAAAAAAAAAAAAAAAAAAOG9YXHhvWD+4r5h/+K+Yf/ivmH/4r5h/+K+YPgAAAAAAAAAAAAAAAAA
AAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivGDc4r5h
/+K+Yf/ivmH/4r5h/+G9Ybj//wABAAAAAAAAAAAAAAAAAAAAAP//AAHhvWC34r5h/+K+Yf/ivmH/
4r5h/+K+YNwAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAADhvGCi4r5h/+K+Yf/ivmH/4b1g79+/XxgAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAADfv18Y4r5g7uK+Yf/ivmH/4r5h/+G8YKIAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivmBH4b1g/uK+Yf/ivmH/4b1h2v//
fwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//38C4b1h2uK+Yf/ivmH/4b1g/uK+YEcAAAAAAAAA
AAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
4rtgNeC8YDIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/
AAAB4b5hxeK+Yf/ivmH/4r5h/+K+Yc3hvWCv4b5gVwAAAAAAAAAA4b5gV+G9YK/hvWHN4r5h/+K+
Yf/ivmH/4r5hxf8AAAEAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAADgu19T4b1g/uG9YP7ivWG/4b1eRgAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5b9fKOK9YPHivmH/4r5h/+K+Yf/ivmH/4r5gfwAAAAAA
AAAA4Lxgf+K+Yf/ivmH/4r5h/+K+Yf/ivmDx5b9fKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9
YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhvV+I4r1h9+K9X23hvWDh4r5h
/+K9YMvivGFR/38AAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN+7X0DivWDx
4r5h/+K+Yf/ivmH/4b1ggQAAAAAAAAAA4b1ggeK+Yf/ivmH/4r5h/+K+YPHju19AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AADivWGI4b5g9QAAAADUqlUG4r1gYuK+YNjivmH/4r5g1OC9X13/vz8EAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAADlv18o4b5hxeG9YP7ivmH/4r5hzeK/XCziuVws4b1hzeK+Yf/hvWD+
4r5hxeW/XygAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivWGI4b5g9QAAAAAAAAAAAAAAAKqqVQPkvWFW4r1gz+G9
YP7ivmDd4b1ead+/XwgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAeK+YEfhvGCi4rxg
3OK+YPjivmD44r5g3OG8YKLivmBH/wAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivWGI4b5g9QAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAOC+X0vivWDE4b1g/uK9YObivWB017BiDQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAADivWGI4b5g9QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4r5hP+K+YLnh
vWD+4b5g7OG9X4DWu10TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH9/
fwLkwWhfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivWGI4b5g9QAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAADhv2I04r5hreG9YP3hvWDy4b1gid+/XwgAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAOG8YYvhvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivWGI4b5g
9QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOC8YSrjvWCk
4b1g/uG9YXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAADivWGI4b5g9QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAeG8YE3hvmDQ4b1g/uK+X1sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/h
vWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivWGI4b5g9QAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADjwGJB4b1gxuK+Yf/hvmDY4b1gVQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADi
vWGI4b5g9QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA475hN+K9YLvhvWD+4b5g4OK9
YGL/qlUDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAADivWGI4b5g9QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOK7YC3i
vV+w4b5g/eK9Yefgvl9u2rZIBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivWGI4b5g9QAAAAAAAAAA
AAAAAAAAAADhvV4j4b1gpOG9YPzivWDu471gedSqVQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAADivWGI4b5g9QAAAAAAAAAA479bHOK9YZjhvWD64b1g8+K9X4Xfv18QAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/h
vWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivWGI4b5g9dq2YRXivV+N4b1g9uK9YffhvWCR3bxY
FwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAOK+Yb/ivmC+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhvmB64r5h/OK9
YPHhvWD74b1gnN69Wh8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv78/BOK+YeLhvGCmAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAADiuFUS4r5goeO9YJzku10mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4b1g
keG9YP7gu19LAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAADivGCO4b1g/uG8X4sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOC8YI7hvWD+4rxgjgAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4rxgjuK+Yf/g
vGCOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9
YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAADivGCO4b1g/uK8YI4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOC8YI7hvWD+4rxgjgAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4rxgjuK+Yf/gvGCOAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AADivGCO4b1g/uK8YI4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAOC8YI7hvWD+4rxgjgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4rxgjuK+Yf/gvGCOAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivGCO
4b1g/uK8YI4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/hvWC/AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAOC8YI7hvWD+4rxgjgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOG9YL/h
vWC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4rxgjuK+Yf/gvGCOAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAOK+YLvivmHCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivGCO4b1g/uK8
YI4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOK+YJbivmDw5LtdEwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAOC8YI7hvWD+4rxgjgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AOC8YSrhvWD24b1gzuG9YFXivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/
4r5hP+K+YT/ivmE/4r5hP+K+YT/fvF5J4r1hqOK+Yf/gvGCOAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADivmBH4b1h4uK+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h
/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4r5h/+K+Yf/ivmH/4b5h9OG9X3gAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/78/BN+7
XTHivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5hP+K+YT/ivmE/4r5h
P+K+YT/jv18468RiDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+AAAAwA8AAPwAAACA
BwAA+AAAAQADAAD4///+AAEAAPn///wAAAAA+f///AAAAAD5///8AAAAAPn///wAAAAA+f///AMA
AAD5///8B4AAAPn///wHgAAA+f///A/AAAD5///8D8AAAPn/P/wDAAAA+f4P/gMBAAD5/gH/AwMA
APn+QH+ABwAA+f5wH8APAAD5/n4H//8AAPn+f4H/nwAA+f5/4H+fAAD5/n/4f58AAPn+f/B/nwAA
+f5/4P+fAAD5/n+B/58AAPn+fgf/nwAA+f54H/+fAAD5/mB//58AAPn+Af//nwAA+f4H//8fAAD5
/h///x8AAPn////+PwAA+f////x/AAD5////+P8AAPn////x/wAA+f///+P/AAD5////x/8AAPn/
//+P/wAA+f///x//AAD5///+P/8AAPn///x//wAA+f//+P//AAD5///x//8AAPn//+P//wAA+P//
x///AAD4AAAP//8AAPwAAB///wAA/gAAP///AAA='''
print(icon)
icondata= base64.b64decode(icon)
## The temp file is icon.ico

tempFile= "icon1.ico"
iconfile= open(tempFile,"wb")
## Extract the icon
iconfile.write(icondata)
iconfile.close()



root=Tk()
root.title("Youtube Download Manager")
#root.iconbitmap(tempFile)
root.call('wm', 'iconbitmap', root._w, tempFile)
root.geometry("720x400+380+100")
os.remove(tempFile)

#****************************************
def on_click(event):
    ent=[play_entry,video_entry]
    for e in ent:
        if e.get() == "playlist link":
            event.widget.delete(0, 'end')
        elif e.get() == "video link":
                event.widget.delete(0, 'end')  
        else:
            e.config(foreground='black')

# create a label
my_label=Label(root,bg="#001541")
my_label.place(x=0,y=0,relwidth=1,relheight=1)

lb=Label(root,text="  Enter Your Link  ",bg="#001541",
          fg="#E8CEA6",bd=7,relief="raise",font=("Segoe Print",24,"bold"))
lb.place(x=0,y=0,relwidth=1,relheight=1)
            #"ridge"  "sunken"  "flat"  "raise" "groove"
lb.pack(padx= 10, pady=20)


#***********
yt_variable1 = StringVar()
yt_variable2 = StringVar()

#playlist entry
play_entry = Entry(textvariable=yt_variable1)
play_entry.config(font=('Helvetica 15 bold')) #change font
play_entry.config(bg='#fff') #background
play_entry.config(fg='#000') #foreground
play_entry.config(width=25)
play_entry.insert(0,'playlist link') #set default text
play_entry.config(foreground='gray')
play_entry.bind("<Button-1>", on_click)
play_entry.bind("<FocusIn>", on_click)
play_entry.pack(padx= 10, pady=10)

#video entry
video_entry = Entry(textvariable=yt_variable2)
video_entry.config(font=('Helvetica 15 bold')) #change font
video_entry.config(bg='#fff') #background
video_entry.config(fg='#000') #foreground
video_entry.config(width=25)
video_entry.insert(0,'video link') #set default text
video_entry.config(foreground='gray')
video_entry.bind("<Button-1>", on_click)
video_entry.bind("<FocusIn>", on_click)
video_entry.pack()

#*****************************

def display_message(msg_name,msg_text):
    message1=tkinter.messagebox.showinfo(msg_name,msg_text)
    return message1

def Exit ():
    Exit=tkinter.messagebox.askyesno("Exit","Really you want to Exit ?!")
    if Exit >0:
        root.destroy()
        return
    
def search_youtube():
    webbrowser.open("https://www.youtube.com/")
    

#download all videos in playlist
def download_playlist():
    #play_entry.get()
    download_location = filedialog.askdirectory() # this will open the Save As dialog

    try:
        p=Playlist(play_entry.get())
   #     counter=0
       # pl=[]
        print(p)
        
        # for video in p.videos:  
        #   #print(p)
        #   pl=p
        #   print(pl)
        
        for pl1 in p:
            # try:
                pl2=YouTube(pl1)
                pl2.streams.filter(res="360p").first().download(download_location)
                
  #              counter=counter+1
#                dw_msg=str(counter)+ ' video downloaded successfully.'
 #               display_message('Completed' , dw_msg)

    except Exception as e:
        display_message('warning','this is not a youtube playlist  or the link may be damaged.')
        print(e)
        raise Exception('Some exception occurred.')
#    p=Playlist(play_entry.get())

    

        #  print(video.thumbnail_url)
       # ys = p.streams.get_highest_resolution()
        #ys.download_all() 
    display_message('Completed','All YouTube videos downloaded successfully.')

#download video
def download_video():
    v = video_entry.get()
    download_location = filedialog.askdirectory() # this will open the Save As dialog

  #  counter=0
    #v=['%url2'] #gets entry
    #v=v_url
    #for url in v:
    try:
        yt_obj=YouTube(v)
        yt_obj.streams.get_highest_resolution().download(download_location)
 #           counter=counter+1
#            display_message('Completed' , dw_msg)
    except Exception as e:
        display_message('warning','this is not a youtube video link or the link may be damaged.')
        print(e)
        raise Exception('Some exception occurred.')

    print('All YouTube videos downloaded successfully.')
 
    display_message('Completed','downloaded successfully.')

#***********************************


bt1=Button(root,text="Download playlist",bg="#E8CEA6",
          fg="#001541",bd=7,relief="groove",font=("Segoe Print",15,"bold"),command=download_playlist)
bt1.place(x=50, y=200)

bt4=Button(root,text="Download video",bg="#E8CEA6",
          fg="#001541",bd=7,relief="groove",font=("Segoe Print",15,"bold"),command=download_video)
bt4.place(x=300, y=200)

# google button
bt3=Button(root,bg="#E8CEA6",text="search_youtube",
         fg="#001541",bd=10,relief="groove",font=("Segoe Print",13,"bold"),command=search_youtube)
bt3.place(x=550,y=200)


# Exit
bt2=Button(root,text="Exit",bg="#E8CEA6",
         fg="#001541",bd=7,relief="groove",font=("Segoe Print",13,"bold"),command=Exit)
bt2.place(x=350,y=300)

root.resizable(False, False)
  
root.mainloop();
